TRUNCATE TABLE
  "BoletaPremio",
  "AsignacionDetalle",
  "AsignacionBoletas",
  "DevolucionDetalle",
  "DevolucionBoletas",
  "MovimientoCaja",
  "Recibo",
  "GastoRecibo",
  "AbonoVendedor",
  "PagoCliente",
  "Venta",
  "Cliente",
  "Gasto",
  "Boleta",
  "Premio",
  "SubCaja",
  "Caja",
  "RifaVendedor",
  "Vendedor",
  "Rifa",
  "Usuario",
  "ConfiguracionSistema"
RESTART IDENTITY CASCADE;
